

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your_secret_key
      - DATABASE_URL=postgres://max:qwerty@db:5432/players

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: players
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
networks:
  ft:
    driver: bridge

volumes:
  db_data: